### PR TITLE
Fixed: `Date` Display in Payment History Card on Profile Page

### PR DESCRIPTION
**Pull request by aliraza556**
### Problem:
- The dates on the payment history are being displayed incorrectly on the profile page. The current format does not properly handle the data returned from the `/api/history` endpoint.

## Issue ticket number and link:
- **Ticket Number:** [ 9 ]
- **Link:** [ https://github.com/Lightning-Bounties/lb-next/issues/9 ]

### Evidence:

image

### Acceptance Criteria
- [x] Correct date format is displayed in the Payment History card.
- [x] Dates align with data from the /api/history endpoint.
- [x] Tested for accuracy with valid and edge-case data.

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @sutt, @lb-founders,

Please review this PR.

**Comment by sutt** [comment]
@aliraza556 Looks great, thanks for your help. I added a small change to get it to work on PaymentsCard.

Check out the [instructions](https://docs.lightningbounties.com/docs/solve-a-bounty/working-on-the-bounty#id-4.1-click-on-claim-reward-and-add-pull-requested-number) for claiming the sats.

Hope to see you racking up more bounties soon.

**Comment by aliraza556** [comment]
> @aliraza556 Looks great, thanks for your help. I added a small change to get it to work on PaymentsCard.
> 
> Check out the [instructions](https://docs.lightningbounties.com/docs/solve-a-bounty/working-on-the-bounty#id-4.1-click-on-claim-reward-and-add-pull-requested-number) for claiming the sats.
> 
> Hope to see you racking up more bounties soon.

@sutt, Ok Thanks!

**Comment by aliraza556** [comment]
Hi @sutt, when I added the PR number in the box and pressed 'Check,' I received an error.

image

**Comment by sutt** [comment]
@aliraza556 I see what went wrong....

By me adding a  comment to this thread after the merge, I am breaking some server-side asserts on integrity checks of the PR.

Problems on our end, we'll get that fixed up by first thing tomorrow so you can claim the reward.

**Comment by aliraza556** [comment]
@sutt, Thanks for the clarification! No worries, I appreciate the quick follow-up and effort to fix it. Looking forward to the resolution tomorrow. Let me know if there’s anything else I can help with. 😊

**Comment by sutt** [comment]
@aliraza556 Sorry for the delays, but you are _officially the bounty winner_ on the app and you should have the _sats in your profile._

### Workarounds:
We discovered two issues with the business logic of our API that prevented this bounty from being awarded automatically. These weren't your error but ours, but listing them below for you so you can adapt until we can put in a patch to our API:
- on PR message write `closes #N` or `close #N`. **Don't** add the colon, so don't say `closes: #N`
- on the PR thread, don't add any comments after the PR has been merged. Feel free to add comments on the issue itself and "@" me though.

### Other Open Bounties:
- #15 looks excellent, merging it in the next 10 minutes. I've already edited the PR message to remove the colon. So once it's merged you should be able to run "Claim Reward" and it should work 🤞. Of course ping me if it doesn't.
- #11 preview image looks like what we need. Feel free to submit as a PR and just remember to remove the colon from the "close #N" in the PR message.

Thanks for your great work and patience🙌.

**Comment by aliraza556** [comment]
> Hi @sutt, when I added the PR number in the box and pressed 'Check,' I received an error 400.
> 
> image
> 
> image

@sutt I get same error with #15 PR

**Comment by aliraza556** [comment]
@sutt, Please see: 
image

**Comment by willbountyhunter** [comment]
@aliraza556 _Bounty awarded, sats should be in your profile_

Thanks for your patience, we're just getting started and hope this runs much smoother soon.

**Comment by aliraza556** [comment]
> @aliraza556 _Bounty awarded, sats should be in your profile_
> 
> Thanks for your patience, we're just getting started and hope this runs much smoother soon.

@willbountyhunter, Thanks

**Pull request merged**
