### PR TITLE
Fixed Mobile Styling on Feed

### LINKED ISSUE #11: Fix Mobile Styling on Feed
We've got overflow going on for the mobile version on:
- [ ] the header
- [ ] the reward amount

Add the necessary flex and media queries to allow the feed to render appropriately on mobile.

image

### PR DESCRIPTION
**Pull request by aliraza556**
### Problem:
- We've got overflow going on for the mobile version on:
   - the header
   - the reward amount

## Issue ticket number and link:
- **Ticket Number:** [ 11 ]
- **Link:** [ https://github.com/Lightning-Bounties/lb-next/issues/11 ]

### Evidence:

https://www.loom.com/share/b98a891ef35845ff98d8a49696195c3b

image

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @sutt, @lb-founders,

Please review this PR.

**Comment by sutt** [comment]
Big improvement, thank you ⚡.

**Comment by sutt** [comment]
@aliraza556 Bounty should be claimed on the app.

**Comment by aliraza556** [comment]
Hi @sutt, how do I withdraw the sats to any wallet? I am currently using Binance. Could you please guide me through the process?

**Comment by sutt** [comment]
@aliraza556 
### Docs here
- [simple withdraw](https://docs.lightningbounties.com/docs/posting-a-bounty/withdraw-funds)
- [in depth withdraw](https://docs.lightningbounties.com/docs/solve-a-bounty/how-to-convert-sats-into-local-currencies)
- We found this link for using [Bianance specifically](https://www.binance.com/en/support/faq/how-to-use-the-bitcoin-lightning-network-to-deposit-and-withdraw-btc-on-binance-7a4eb2d9ccaf4433908b448aa3a93493)

### Additional Guidelines
- Keep withdraws < 90,000 sats. 
  - But you can do this multiple times if you need to withdraw more than that.
- Sometimes fee rates can make getting the full 90,000 difficult, in this case try 9,000 sats and see if that works.

Also check your gmail inbox.

**Pull request merged**
